jobs:
  - name: test
    type: runSh
    integrations:
      - test_kv
    steps:
      - IN: test_kv
      - TASK:
          script:
            - META=$(shipctl get_resource_meta test_kv)
            - echo $META/integration.env
