resources:
  - name: test_kv
    type: integration
    integration: test_kv
    
jobs:
  - name: test
    type: runSh
    steps:
      - IN: test_kv
      - TASK:
          script:
            - META=$(shipctl get_resource_meta test_kv)
            - echo $META/integration.env
            - cat $META/integration.env
            - echo "foo: $foo"
            - echo "baz: $baz"
